title: Jekyll Theme Manpage
description: Jekyll theme based on the manpage style for personal websites.
author: Your Name
show_downloads: false
google_analytics:
theme: jekyll-theme-manpage
quiet: true
favicon:
  svg: assets/images/favicon.svg
# url: 
plugins:
  - jekyll-katex  
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-feed
features:
  comments: true  # Set to true to enable Giscus comments
  rss_feed: false  # Set to true to enable RSS feed
excerpt_separator: "<!--more-->"
toc:
  min_level: 1 # default: 1
  max_level: 3 # default: 6
  ordered_list: false # default: false
  no_toc_section_class: no_toc_section # default: no_toc_section
  list_class: section-nav # default: section-nav
  sublist_class: '' # default: ''
  item_class: toc-entry # default: toc-entry
  item_prefix: toc- # default: toc-